# Generated by Django 3.1.7 on 2021-04-17 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditor',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Username must be between 3 and 20 alphanumeric characters, plus - and _.', regex='^[A-Za-z0-9\\-\\_]{3,20}$')]),
        ),
    ]
